name: Deploy Landing to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - "frontend/landing/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/landing

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build # ← this must produce the dist/ directory

      - name: Deploy to Cloudflare Pages
        run: npx wrangler@4 pages deploy dist --project-name=atomicflow --branch=main
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
